### ISSUE TITLE
Adding timers from list of timers screen

### ISSUE THREAD

**Issue by mg6maciej** [elpassion/cloud-timer-android#15]
- user should be able to open timer starting screen from list of timers screen

**Comment by mg6maciej** [comment]
@jasiekpor Where are the commits? ;)

**Comment by rafaltrzcinski** [comment]
I forgot add task number.
Commit: 
https://github.com/elpassion/cloud-timer-android/commit/48bd600776cdff05841f2f19b5c993a0ae0164e1

**Comment by mg6maciej** [comment]
When new timer is added and it's alarm date is after currently running timer, the new one overrides old timer scheduling and the first timer won't fire notification.
