### ISSUE TITLE
Slack notifications from Coveralls not working

### ISSUE THREAD

**Issue by mg6maciej** [elpassion/cloud-timer-android#28]
Travis doesn't send notification on success

**Comment by mg6maciej** [comment]
Not complete according to acceptance criteria.

**Comment by jasiekpor** [comment]
fixed

**Comment by rafaltrzcinski** [comment]
Nope - when build failed  there is no notifications on  slack

**Comment by rafaltrzcinski** [comment]
Fixed, on develop
