### ISSUE TITLE
Crashlytics BETA integration

### ISSUE THREAD

**Issue by mg6maciej** [elpassion/cloud-timer-android#8]
Send builds to crashlytics
Notify selected group of testers about new builds
Add commit message to a build

**Comment by mg6maciej** [comment]
@rt90 
Does not notify selected group of testers about new builds. I created group named "team" for that purpose.
Does not add commit message to release notes of a build. See attached screenshot.

**Comment by mg6maciej** [comment]
<img width="1106" alt="screen shot 2016-01-28 at 15 29 37" src="https://cloud.githubusercontent.com/assets/1316369/12647157/0e3b5846-c5d4-11e5-8d41-a404bb690a4d.png">

**Comment by HelenaKot** [comment]
TODO : jak zdoby release note z githuba
